/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-07-25 04:14:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.css;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 
public String headroot(HttpServletRequest request){
	return request.getContextPath();
}


public static final String ORACLE_DRIVER = "oracle.jdbc.driver.OracleDriver";
public static final String ORACLE_URL = "jdbc:oracle:thin:@localhost:1521:xe";
public static final String DB2_DRIVER = "";
public static final String DB2_URL = "";
public static final String MYSQL_DRIVER = "";
public static final String MYSQL_URL = "";
public static final String MSSQL_DRIVER = "";
public static final String MSSQL_URL = "";
public static final String MARIADB_DRIVER = "";
public static final String MARIADB_URL = "";
public static final String USERNAME = "hanbit";
public static final String PASSWORD = "hanbit";
public static final String TABLE_MEMBER = "Member";
public static final String MEMBER_ID = "id";
public static final String MEMBER_PASSWORD = "password";
public static final String MEMBER_NAME = "name";
public static final String MEMBER_SSN = "ssn";
public static final String MEMBER_REGDATE = "regdate";
public static final String TABLE_BOARD = "Board";
public static final String BOARD_ARTICLE_SEQ = "article_seq";
public static final String BOARD_ID = "id";
public static final String BOARD_TITLE = "title";
public static final String BOARD_CONTENT = "content";
public static final String BOARD_REGDATE = "regdate";
public static final String BOARD_HITCOUNT = "hitcount";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/css/../member/../common/common_service.jsp", Long.valueOf(1500946862643L));
    _jspx_dependants.put("/css/../member/member_head.jsp", Long.valueOf(1500952215747L));
    _jspx_dependants.put("/css/../constants/db.jsp", Long.valueOf(1500953191753L));
    _jspx_dependants.put("/css/../common/footer.jsp", Long.valueOf(1500944715571L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.beans.Statement");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Student detail</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(headroot(request));
      out.write("/css/member.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h1 id=\"title\">학생 관리 </h1>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t</div>\t<a id=\"go_main\" href=\"");
      out.print(headroot(request));
      out.write("/index.jsp\">메인으로 가기</a><br />\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("      ");
      out.print(new SimpleDateFormat("yyyy년 MM월 dd일 a hh:mm:ss").format(new Date()));
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"container\">\r\n");
      out.write("   <button class=\"gms-index-button\" onclick=\"window.location.href='member/member_detail.jsp'\">마이페이지</button>\r\n");
      out.write("   <br />\r\n");
      out.write("   <hr>\r\n");
      out.write("   <table id=\"index-tab\">\r\n");
      out.write("      <tr id=\"main-bar\">\r\n");
      out.write("         <th><i class=\"glyphicon glyphicon-user\"></i>학생관리</th>\r\n");
      out.write("         <th><i class=\"glyphicon glyphicon-cloud\"></i>성적관리</th>\r\n");
      out.write("         <th><i class=\"glyphicon glyphicon-thumbs-up\"></i>게시판</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr class=\"main-list\">\r\n");
      out.write("         <td>\r\n");
      out.write("            <ul class=\"index-ul\">\r\n");
      out.write("               <li><a href=\"member/member_login.jsp\">관리자 로그인</a></li>\r\n");
      out.write("               <li><a href=\"member/member_add.jsp\">학생정보 추가</a></li>\r\n");
      out.write("               <li><a href=\"member/member_list.jsp\">학생정보 목록</a></li>\r\n");
      out.write("               <li><a href=\"member/member_detail.jsp\">학생 상세정보</a></li>\r\n");
      out.write("               <li><a href=\"member/member_update.jsp\">학생정보 수정</a></li>\r\n");
      out.write("               <li><a href=\"member/member_delete.jsp\">학생정보 삭제</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </td>\r\n");
      out.write("         <td>\r\n");
      out.write("            <ul class=\"index-ul\">\r\n");
      out.write("               <li><a href=\"grade/grade_add.jsp\">성적 입력</a></li>\r\n");
      out.write("               <li><a href=\"grade/grade_list.jsp\">성적 목록</a></li>\r\n");
      out.write("               <li><a href=\"grade/grade_detail.jsp\">성적 상세</a></li>\r\n");
      out.write("               <li><a href=\"grade/grade_update.jsp\">성적 수정</a></li>\r\n");
      out.write("               <li><a href=\"grade/grade_delete.jsp\">성적 삭제</a></li>\r\n");
      out.write("            </ul>   \r\n");
      out.write("         </td>\r\n");
      out.write("         <td>\r\n");
      out.write("            <ul class=\"index-ul\">\r\n");
      out.write("               <li><a href=\"board/board_write.jsp\">게시글쓰기</a></li>\r\n");
      out.write("               <li><a href=\"board/board_list.jsp\">게시글목록</a></li>\r\n");
      out.write("               <li><a href=\"board/board_update.jsp\">게시글수정</a></li>\r\n");
      out.write("               <li><a href=\"board/board_delete.jsp\">게시글삭제</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td></td>\r\n");
      out.write("         <td></td>\r\n");
      out.write("         <td></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   </div>\r\n");
      out.write("   <hr />\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p>Posted by: Hanbit</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tContact information: <a href=\"mailto:someone@example.com\">\r\n");
      out.write("\t\t\t\t\t\thanbit@example.com</a>.\r\n");
      out.write("\t\t\t\t<a href=\"util/jdbc_test.jsp\">DB 연결테스트</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
